### ISSUE TITLE
Bad unknown6 signature builder

### ISSUE THREAD

**Issue by waryas** [cyraxx/pogobuf#102]
I'm not really using this library but I should let you know that node-pogo-signature is deprecated in the way seeds+signature is generated and is detectable.

You should probably fork it and do the fixes.

Seeds changed for the xxhash function, the githash commit id (uk25) isn't set (And it is set since version 0.33.0).

**Comment by cyraxx** [comment]
@SpencerSharkey what do you say?

**Comment by SpencerSharkey** [comment]
Sorry, I'm so late here...

I did update node-pogo-signature with the updated hash seed (for the xxhash utils). Since this repo relies on ^2.0.0 a simple npm update should at least fix your hash seeds.

I am unaware of the uk25 addition. I'll take a look into this when I can find some free time. Anyone is welcome to fork and submit a pr :)

**Comment by joelfi** [comment]
A fork was made and node-pogo-signature was updated. See 
5530068aabebf0442cacb3975e1242cda9438d29.
