### ISSUE TITLE
Get player profile and badges

### ISSUE THREAD

**Issue by akarupt** [cyraxx/pogobuf#103]
Is it normal that `getPlayerProfile` function only return me badges and always 0?

**Comment by AmazingGamerBoy** [comment]
you should be using getPlayer() instead, but nevertheless I am also getting the same error. I believe that pogobuf API needs to be updated to fix this bug.

**Comment by AmazingGamerBoy** [comment]
@akarupt I think i'm onto something... the inventory.js example correctly shows the player level. Give me some more time and I will figure it out for u!

**Comment by AmazingGamerBoy** [comment]
@akarupt I figured it out, and the level of the player can be found at -> inventory.player.level

**Comment by joelfi** [comment]
I'm not sure what the issue is. Are you getting response of `0`, only badges or 0 badges? You should look into the documentation. If you want badges, you cannot use [getPlayerProfile](https://github.com/cyraxx/pogobuf/wiki/pogobuf.Client-Pokémon-Go-API-Methods#getplayerprofileplayername--promise), because it does not fetch player's badges. Use [getPlayer](https://github.com/cyraxx/pogobuf/wiki/pogobuf.Client-Pokémon-Go-API-Methods#getplayer--promise) instead.

**Comment by joelfi** [comment]
No response from original author and it seems like there isn't an issue anymore.
