### ISSUE TITLE
Latest API & Safety

### ISSUE THREAD

**Issue by DanForbes** [cyraxx/pogobuf#104]
I came across [a comment that was recently added to the README.md for Blossom's PoGO Manager](https://github.com/Wolfsblvt/BlossomsPokemonGoManager#important-note-on-using-this-tool), the gist of which is that since Niantic forced everyone to update their apps, using third-party tools is less safe than before.

Now, I know that there is no "safe" way to use a third-party tool like `pogobuf`, but I'm curious if the devs have any thoughts on this issue and/or if an update is in the works.

**Comment by Vankxr** [comment]
I don't know about "safety" since all APIs/Bots are unofficial, they always have a way to identify illegal network traffic.

What I know is that Niantic is now banning phone IDs/IMEIs or something else. I don't know if they were doing it before, but I can't login anymore from my phone, in any version, with or without root or any other modification.

PS: I didn't try to factory reset it, because I'm lazy to do that :(

**Comment by joelfi** [comment]
As far as we know, newest node-pogo-signature should replicate unknown6 perfectly. It's up to you how you use the api and how obvious you make it that you're using a third party api.
