### ISSUE TITLE
Encounter results in err (pokeball_type)

### ISSUE THREAD

**Issue by renedx** [cyraxx/pogobuf#2]
Whenever you try to encounter, it is unable to decode the SRV response.

```
Error: Illegal wire type for field Message.Field .POGOProtos.Data.Capture.CaptureProbability.pokeball_type: 2 (0 expected)
```

Prob an error at https://github.com/AeonLucid/POGOProtos, but as I'm unable to find the exact cause (maybe needs rebuild at https://github.com/cyraxx/node-pogo-protos).

Dummy reprod code;
```javascript
    .then(mapObjects => {
        var hasPokemon = null;
        mapObjects.map_cells.forEach(cellData => {
          if (cellData.catchable_pokemons.length) {
            hasPokemon = cellData.catchable_pokemons[0];
          }
        });

        if (hasPokemon) {
          return client.encounter(hasPokemon.encounter_id, hasPokemon.spawn_point_id);
        }

        return 'nothing encountered';
    }).then(res => {
        console.log(res);
    })
```

**Comment by cyraxx** [comment]
Reproduced the bug, it's caused by protobuf.js when the .proto files are missing `packed` attributes (other Protobuf implementations seem to be more lenient).

I've created a [PR for POGOProtos](https://github.com/AeonLucid/POGOProtos/pull/58) but also manually [fixed it in node-pogo-protos](https://github.com/cyraxx/node-pogo-protos/commit/911888ddf6c2152098ddbf19c309813461077386) for now so if you update node-pogo-protos to 1.0.2 via npm it should be fine.

**Comment by renedx** [comment]
Nice :)
I ran into the same problem while handeling catch response. Had to comment `.POGOProtos.Data.Capture.CaptureAward capture_award = 4;` of `CatchPokemonResponse` to make it work. Prob requires [packed] too, not too familiar with protos tbh.

**Comment by renedx** [comment]
Running into yet another one;
```
Illegal wire type for field Message.Field .POGOProtos.Networking.Responses.CheckAwardedBadgesResponse.awarded_badges: 2 (0 expected)
```
