### ISSUE TITLE
Randomly generate Request ID

### ISSUE THREAD

**Issue by cyraxx** [cyraxx/pogobuf#26]
Currently the `request_id` in the request envelope is hard coded when it should probably be a random value for each request. The only question is what range to use, aka how does the original app do it?

**Comment by renedx** [comment]
I was thinking someone prob fixed that already.. oh... ..
https://github.com/search?p=1&q=8145806132888207460&type=Code&utf8=%E2%9C%93

**Comment by Morgul** [comment]
Does the server care what we send for this? I'd imagine we could start at 0 and count.

**Comment by MakuraYami** [comment]
@renedx that's hilarious lol, I sometimes forget you can search github. 

@Morgul the server does not seem to care, it's just an identifier for the request. But it is important to mimic the original app because this is one of many ways niantic can detect that you're not legit, aka a bot. Counting up won't do much good either since its too different from how the app does it. 

We need to inspect what the normal app sends, set up a mitm server that logs all requests, play for a while on your phone while using it and see the range of the ids that have been used. Based on that we can figure out a function to generate something similar.

**Comment by renedx** [comment]
This issue may have just been timed perfect, as Niantic introduced API throttling. Wondering if Request ID has to do anything with it.

On the Java API it is now changed to an incremental counter:
https://github.com/Grover-c13/PokeGOAPI-Java/pull/328/files#diff-532a32906d5cefbfb9887e55df86246aR289

**Comment by cyraxx** [comment]
We have a pretty solid version in place now (randomize, then increase for each request). Only issue is that our randomizer sometimes produces shorter numbers than what the app uses. Would probably be an easy fix if someone wants to do it.

**Comment by MakuraYami** [comment]
I'm highly against increase for each request to be honest, since this is NOT what the app does. It sends a random one each time.

**Comment by cyraxx** [comment]
Well that would be a pretty easy change :)
