### ISSUE TITLE
Add Long to dependencies, bump version

### ISSUE THREAD

**Issue by devdaniel** [cyraxx/pogobuf#34]
long is required but not in node package dependency list
Not sure what you're using for determining version numbers

**Comment by cyraxx** [comment]
I thought it was already in there, apologies. Added it now.
However it's only been required since https://github.com/cyraxx/pogobuf/commit/f097b414050e570753a68401d49912a4f1bea3d7 which hasn't been released yet so it should be fine to just include this in the next release, no?

Version numbers are [semver](http://semver.org/) btw.
