### ISSUE TITLE
wild pokemon radius search

### ISSUE THREAD

**Issue by keithics** [cyraxx/pogobuf#4]
I have been changing the example to widen the search for wild pokemons -- but with no good results.

Do you have an example where the getMapObjects search result is based on 2km radius?

Thank you. awesome work!

**Comment by cyraxx** [comment]
I'm afraid I don't have an example for that. To be honest all the logic in `example.js` that gets the S2 cell IDs for the map radius search I simply copied over from pgoapi's [pokecli.py](https://github.com/tejado/pgoapi/blob/master/pokecli.py) so I couldn't even tell you how big exactly the radius is now.

It's also possible that there is a limit to how many map cells you can query at once (or how far away from your current player position they can be) so you might have to make multiple calls.

**Comment by renedx** [comment]
AFAIK there is a limit based on the current (provided) position. Current radius is pretty huge IMHO, otherwise you could use the nearby. It provides you with Pokémon nearby that do fall into km radius 

If you use the distance to the cell that provided the nearby, you're able to calculate the probability of a Pokémon nearby a certain cell and base your search on that. Hope this helps.

**Comment by cyraxx** [comment]
Someone on Slack mentioned that you can search for up to 100 level 15 cells at once.
