### ISSUE TITLE
Retry automatic failed requests interval

### ISSUE THREAD

**Issue by Tuxity** [cyraxx/pogobuf#54]
Hi,

After the implementation of the automatic retry if request fail, I've a looot of error 52 from niantic. Maybe we should change the base interval from 300ms to 5000ms (actual throttling of niantic since this weekend)

Before this feature, with a basic throttle logic I almost didn't had this error. I'm I missing something ?

**Comment by Morgul** [comment]
Isn't the 5s throttling only specific requests (i.e. `getMapObjects`)? I didn't think that had been moved to all requests.

**Comment by Tuxity** [comment]
Hmm you're right, maybe it's specific to getMapObjects

**Comment by jimdubbs** [comment]
It is specific to just getMapObjects AFAIK.

**Comment by Tuxity** [comment]
Now it seems to be 10sec for getMapObjects, maybe it could be nice to keep a function to set the retry interval no ?

**Comment by Morgul** [comment]
I've been hearing 7 seconds work, but yeah, it might be nice to be able to configure the retry values. 

Though, to be fair, bluebird's [Promise.delay](http://bluebirdjs.com/docs/api/promise.delay.html) is more than sufficient enough for this. I think that controlling the timing by API is a bit beyond the scope of the project, and this is a good enough work around.

**Comment by cyraxx** [comment]
Well it's an interesting question: Generally I don't want to include any game logic or "human simulation" in the client itself. On the other hand however, my objective has always been that the client should enable you to make API calls without getting error messages so it should prevent errors if it can.

We could introduce a throttling specifically for `getMapObjects`, and fetch the minimum time between calls from the game settings (which we download during `init()` anyway) so that we automatically have the right number if Niantic changes it again.

**Comment by renedx** [comment]
We should definitely use the MAX reload given from the downloads during init IMHO. Thats your safest bet.

**Comment by Tuxity** [comment]
I don't see it as human simulation, it's more add possibility to set a lot of options and handle more errors.

I don't know that is the best way to do that, your solution looks good to me @cyraxx

**Comment by cyraxx** [comment]
@renedx I was under the assumption that the minimum should be enough to avoid errors and it's also what the app uses so we could go with that and not delay calls any longer than necessary.

Am I mistaken? Are you getting errors when using the minimum?

**Comment by cyraxx** [comment]
Implemented this using the minimum delay from the settings response. Seems to work well in my tests.
