### ISSUE TITLE
Refactor login/auth system

### ISSUE THREAD

**Issue by cyraxx** [cyraxx/pogobuf#8]
Turn the two login classes into something like `AuthProvider`s so that you simply pass it to the `Client` class instead of explicitly having to specify the auth type again in `client.setAuthInfo()`.

Further possible enhancements:
- Instead of exposing the login classes just pass auth type (`ptc` or `google`), username, and password to the `Client` constructor instead
- Implement auth token caching instead of having to login every time you run the app
- Have the `Client` automatically ask the `AuthProvider` to renew the token if it's no longer valid

**Comment by MakuraYami** [comment]
Besides Auth token caching we could also consider caching the endpoint "url" and "auth_ticket", that way it could technically resume without reauthenticating. The auth_ticket is valid for 30 minutes since the last api call, it gives the expire info so you can even prevent running into errors and relog automatically based on that.

**Comment by jimdubbs** [comment]
I'm going to take a crack at this this afternoon if nobody else is!

**Comment by jimdubbs** [comment]
Ran into an issue and im not sure what the correct answer is. Once a request comes back with a 102 and re need to re-authenticate..do we need to get a brand new session, or just request a ticket with the original session?

I ask because when trying to just re-execute the login process after a 102 the PTC returns a 500 error...and I'm not entirely sure why. Anyone have any insight?

**Comment by Tilotiti** [comment]
> Instead of exposing the login classes just pass auth type (ptc or google), username, and password to the Client constructor instead

You can define the auth type by a simple test.

`var type = (username.indexOf('@') > -1) ? 'google' : 'ptc'`

Isn't that enough ? Maybe an "auto" to auto-determinate the auth type ?

**Comment by mifi** [comment]
@jimdubbs I got the same error (500) and it seems to be because the request.jar() is persistent.
So what I did was to reinstantiate the PTCLogin class, then re-run all the auth steps, like this:

  login = new pogobuf.PTCLogin();
  return login.login(username, password).then(token => {
    client.setAuthInfo('ptc', token);
    client.setPosition(lat, lng);
    return client.init();
  });

This creates a new cookie jar every time, and seems to be working.

**Comment by cyraxx** [comment]
Oh you're right, I forgot about the jar! `setAuthInfo()` resets the auth ticket (since a few commits ago) but not the jar. That's a bug.

**Comment by jimdubbs** [comment]
ahh makes sense, thanks!

**Comment by cyraxx** [comment]
I've fixed `pogobuf.PTCLogin` so that `login()` now always resets the jar first.

**Comment by dabnoj** [comment]
@Tilotiti man once you dont need to put @ in google auth, i think that is not a good way to handle it ;)

**Comment by Jekins** [comment]
How create google 2-step verification? If i use [this google sign-in button](https://developers.google.com/identity/sign-in/web/sign-in) and send token (id_token) from this button here, I got 102 error:
```
const token = 'token from google button sign-in';

this.client.setAuthInfo('google', token);
this.authed = token;
return this.client.init();
```

P.S.: sorry for my English

**Comment by joelfi** [comment]
If you are asking how to login with a Google account with 2FA enabled, you should generate an application-specific password in your Google account [here](https://security.google.com/settings/security/apppasswords). More information [here (EN)](https://support.google.com/accounts/answer/185833?hl=en) and [here (RU)](https://support.google.com/accounts/answer/185833?hl=ru).

**Comment by Jekins** [comment]
@joelfi I know about this method. But this is difficult for users. Can I craete auth with Google btn?

**Comment by cyraxx** [comment]
If you have a way of getting a master token, you could use `GoogleLogin.loginWithToken()`. However I don't know if what you get from the button is a master token.

**Comment by edswartz** [comment]
What you get from the Google Sign On button is a token_id that can be used to return a json obj to verify integrity of account and expiration. So it can be installed to authenticate into a local app, but not sure how a token_id could be passed to niantic to match/authenticate on their side. Is that the issue or am I over thinking it?

**Comment by cyraxx** [comment]
Closing all issues as this repository is no longer being maintained. See README for further information.
