### ISSUE TITLE
Cannot login anymore

### ISSUE THREAD

**Issue by maierfelix** [cyraxx/pogobuf#81]
````
Error: operation timed out after 9016 ms, 5 tries with error: Cannot read property 'push' of null.

TypeError: Cannot read property 'push' of null
       at self.signatureBuilder.encrypt (C:\Users\xxxx\Downloads\pogobuf-latest\node_modules\pogobuf\pogobuf\pogobuf.client.js:886:34)
````

Happens for both providers.

**Comment by cyraxx** [comment]
The problem comes from a proto update: [RequestEnvelope.unknown6 is no longer repeated](https://github.com/cyraxx/node-pogo-protos/commit/5eaba0ba9de37995d91b6df037faf80742e85bda#diff-e41942a078fa60f0b8b24cee645873f8L21).

See [the latest commit](https://github.com/cyraxx/pogobuf/commit/cfd4abaf675d263028a0e4451bf74ec2b886eaf1#diff-d8c5826db958f7a8bf71c29d4b4b1a88) for a fix. I'll make a patch release in a bit.
