### ISSUE TITLE
Unhandled rejection StopError: Status code 3 received from RPC

### ISSUE THREAD

**Issue by dwuster** [cyraxx/pogobuf#83]
I receive this error trying catch a pokemon..
I modify de exemple code...

```
return bluebird.resolve(cell.catchable_pokemons).each(poke => {
    console.log(client.catchPokemon(poke.encounter_id, 1, 1, poke.spawn_point_id, true, 1, 2))
})
```

**Comment by cyraxx** [comment]
It sounds like you're not calling `encounter()` before `catchPokemon()`. You need to encounter a Pokémon before you can catch it.

Also, with mass calls like that it might be a good idea to use [batch mode](https://github.com/cyraxx/pogobuf/wiki/Usage#batch-mode).

**Comment by dwuster** [comment]
```
return bluebird.resolve(cell.catchable_pokemons).each(poke => {
     client.batchStart()
     .encounter(poke.encounter_id,poke.spawn_point_id)
     .catchPokemon(poke.encounter_id, 1, 1, poke.spawn_point_id, true, 1, 2)
})
```

**Comment by dwuster** [comment]
```
return bluebird.resolve(cell.catchable_pokemons).each(poke => {
    return bluebird.resolve(client.encounter(poke.encounter_id,poke.spawn_point_id)).then(response => {
            var poke = response.wild_pokemon;
            console.log(client.catchPokemon(poke.encounter_id, 1, 1, poke.spawn_point_id, true, 1, 2));
    });
});
```
the response : 
```
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
Unhandled rejection StopError: Status code 3 received from RPC
```
U can help me on batch mode?

**Comment by adnanbrq** [comment]
Hello, I've encountered this Issue too but I've done anything as it should probably be done.
First I call the encounter Method and if it succeeds then I call catchPokemon.
There was only one problem. I've got that Status 3 Error message.

To solve this problem you have to follow the steps below

1. First encounter
2. Make sure you have enough pokeballs of the specified one, because if you don't then you'll get this Status 3 Error.

**Comment by dwuster** [comment]
You can give me a code example?

**Comment by adnanbrq** [comment]
Take a look at [this pull request](https://github.com/rdeeb/node-pkgo-bot/pull/4/files)

**Comment by MakuraYami** [comment]
Thank you for the answers @adnanbrq, you are correct and the PR does seem similar to how it would be when using pogobuf. 

@dwuster, what do you think bluebird.each will do to begin with? Console logging a promise obviously shows the promise object. You should probably look over what a promise is first, but let me try to give a fast rundown. The promise itself has no value until it is resolved, which is why it's called a promise. It's a promise for a returned value in the future, usable by using `then`. Bluebird.each according to your code samples will go over catchable pokemon and for each one of them call the batch (where you're forgetting to so the call method but I'll leave that out for now.)  The server won't expect a encounter and catch in a batch because that's impossible from the app, first point of failure. When the pokemon escapes the ball and you should throw again, you ignore it and encounter the next. Second point of failure. With more then one pokemon it will do 4+ consecutive calls and trigger the throttling rules giving 52 errors. Third point of failure. Then when andanbrq gives an excellent response you ask for a code example. These issues are not a getting started with javascript helpdesk... That said, if you run into other issues with pogobuf we'll be happy to help you.

**Comment by dwuster** [comment]
@MakuraYami Thank you for the explanation! I did not know the promise method, I will study more!
